### ISSUE TITLE
Feature Request: Update API requests with new params

### ISSUE THREAD

**Issue by johnmoney83748932** [chrisrude/oobabot#40]
Ooba recently implemented new generation params, top_a and tfs into webui and API:

https://github.com/oobabooga/text-generation-webui/commit/486ddd62df3cc472ffa0a79190e2957b6f1f90ed

**Comment by chrisrude** [comment]
Thanks for the heads up!  This is done in https://github.com/chrisrude/oobabot/commit/9ab486ae3520fa36d03e5696aeb9342793833a3f

There were actually a few other missing params too.

BTW, you probably know this already, but for others reading... if you want to just use the new params, you don't need to wait until the new release.  Just copy the following into your config.yml file (replacing the existing oobabooga request_params section) and have at it.

```
  request_params:
    max_new_tokens: 250
    do_sample: true
    temperature: 1.3
    top_p: 0.1
    typical_p: 1
    epsilon_cutoff: 0
    eta_cutoff: 0
    tfs: 1
    top_a: 0
    repetition_penalty: 1.18
    top_k: 40
    min_length: 0
    no_repeat_ngram_size: 0
    num_beams: 1
    penalty_alpha: 0
    length_penalty: 1
    early_stopping: false
    mirostat_mode: 0
    mirostat_tau: 5
    mirostat_eta: 0.1
    seed: -1
    add_bos_token: true
    truncation_length: 2048
    ban_eos_token: false
    skip_special_tokens: true
    stopping_strings: []
```
