### ISSUE TITLE
SD Params

### ISSUE THREAD

**Issue by TruthSearchers** [chrisrude/oobabot#59]
Hey Chris ,how are you , I want to add this sd params in 

    'denoising_strength',
    'restore_faces',
    'enable_hr',
    'hr_upscaler': 'ESRGAN_4x',
    'hr_scale',
    'seed',
    'sampler_name': 'DPM++ 2M Karras',
    'cfg_scale'

As it will give more better generation 
Any suggestion how to do it ?

**Comment by jmoney7823956789378** [comment]
You can just add them to the listed params in your config.yml, but make sure to follow the existing format of other params in config.yml.
For enable_hr, I believe it's a boolean "true" or "false".

**Comment by TruthSearchers** [comment]
Yup I did it , but it's not working 
Sampler param I checked is not working 
It's only using default one even if set to something other

**Comment by jmoney7823956789378** [comment]
> Yup I did it , but it's not working Sampler param I checked is not working It's only using default one even if set to something other

http://10.20.230.243:7860/docs#/default/text2imgapi_sdapi_v1_txt2img_post
You should be using these params from the official API docs.
Your config.yml will probably look something like this:

```
  request_params:
    do_not_save_samples: true
    do_not_save_grid: true
    negative_prompt: easynegative, ng_deepnegative_v1_75t, badhandv4, lowres, ((nfsw))
    negative_prompt_nsfw: easynegative, ng_deepnegative_v1_75t, badhandv4
    steps: 30
    width: 512
    height: 512
    sampler: DPM++ SDE Karras
    cfg_scale: '8'
    CLIP_stop_at_last_layers: 1
    restore_faces: true
    enable_hr: true
    hr_scale: 1.5
    hr_sampler_name: ESRGAN_4x
```
